version: '3.3'
services:
  redis:
    image: terrabrasilis/redis:v01
    container_name: redisdb
    ports:
      - '6379:6379'
    volumes:
      - "/home/andre/Dados/tmp/redisdb:/data"
    #entrypoint: redis-server --appendonly yes
  
  redis-api:
    image: terrabrasilis/redis-api:v01
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
