version: '3.3'
services:
  redisdb:
    image: terrabrasilis/redis:v01
    container_name: redisdb
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - "/home/andre/Dados/tmp/redisdb:/data"

  redis-api:
    image: terrabrasilis/redis-api:v01
    container_name: redisapi
    ports:
      - "3000:3000"
    links:
      - redisdb
    restart: always
    environment:
      - REDIS_HOSTNAME=192.168.15.49
      - REDIS_PORT_6379_TCP_ADDR=192.168.15.49
      - REDIS_PORT=6379
      - REDIS_PORT_6379_TCP_PORT=6379
    # environment:
    #   DASHBOARD_API_PORT: 3000
    #   DASHBOARD_API_REDIS_HOST: redisdb
    #   DASHBOARD_API_REDIS_PORT: 6379
    

  # The new version 1.1.0 is used to push only once to redisdb and do not use filters
  # redis-feeder:
  #   image: terrabrasilis/redis-feeder:v1.1.0
  #   container_name: feeder
  #   links:
  #     - redis-api
  #   ports:
  #     - "8090:8080"
  #   environment:
  #     - "HOST_REDIS_API=http://192.168.15.49:3000"
      #- "SPRING_PROFILES_ACTIVE=prod"
