version: '3.2'
services:
  redis-feeder-homologation:
    image: terrabrasilis/redis-feeder:h1.0.0
    ports:
      - "8080"
    networks:
      - proxy
    environment:
      - "SPRING_PROFILES_ACTIVE=homol"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true